### ISSUE TITLE
Oblige - Map generator

### ISSUE THREAD

**Issue by fervi** [Blasphemer/blasphemer#20]
Hello.

Generally Blasphemer works fine in terms of graphics. The biggest problem is the lack of maps. Maybe you have to try to generate maps and better to put into the project? This will save time and the game will be playable.

https://sourceforge.net/projects/oblige/?source=directory

**Comment by Blasphemer** [comment]
Hello, sorry for the late response.

As a placeholder, sure, it could be done. This reminds me that Samian put some work on it's version of Oblige called ObHack https://github.com/samboy/ObHack/releases/tag/ObHack-008-Blasphemer201602 that supports Heretic and Blasphemer, so it may be worth a try.
Additionally the first two episodes are fully playable from start to finish (barring the secret levels wich are placeholders).

-Cacowad.

**Comment by fervi** [comment]
Well, i can't play on "experimental" branch, so I use master, and maps there doesn't exists (i mean it is short default map for 3-4 maps, and then you can go to normal map)

**Comment by Blasphemer** [comment]
There is a reason you cannot play the "experimental" one? Like a compilation bug or a run-time error of some sort?

-Cacowad.

**Comment by fervi** [comment]
R_InitSprites: Sprite IMPX frame B is missing rotations

I try to run it on heretic-vanilla from debian.

**Comment by Blasphemer** [comment]
During the last update i somehow managed to omit the IMPXB1 frame from the wadinfo. I've tested it with heretic+, so it should be fine.
Please let me know if you encounter any other problem.

-Cacowad

**Comment by fervi** [comment]
Do you know any good engine for Blasphemer? Heretic Chocolade (Doom Chocolade) crashing

Doomsday it too hard for me (you know, you work on Linux 15 years, but you can't add game for Doomsday lol)

**Comment by Blasphemer** [comment]
If you own an original copy of heretic, you can patch the original .exe using this: 
https://sourceforge.net/projects/prboom-plus/files/heretic-plus/1.32.1/
(the patch raise by a lot the standard vanilla limits, nothing more)
Then, just rename the blasphemer iwad as heretic.wad and you are good to go.
Otherwise zdoom will suffice: https://zdoom.org/downloads
To avoid any potential name related problems, just rename the blasphemer iwad as heretic.wad.

-Cacowad

**Comment by fervi** [comment]
Now Blasphemer (with zdoom engine) works very good, thanks ;)
