### ISSUE TITLE
IMPXH0 offset is bad

### ISSUE THREAD

**Issue by RagnarRandom** [Blasphemer/blasphemer#26]
the offset for IMPXH0 sprite (imp falling after you kill it) is bad. when it falls it goes way off to the side.

![badoffset](https://user-images.githubusercontent.com/98027513/155633941-9e540033-4aa3-4077-a5d7-c276703df4c5.png)

**Comment by Blasphemer** [comment]
Imp was replaced in the latest commit. Issue closed.
