### ISSUE TITLE
Weapons graphics are needed.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Blasphemer/blasphemer#3]
```
A full set of weapon HUD graphics are required for version 0.2 (Deathmatch 
readiness.)

Matching them with the weapon pickup sprites already in Blasphemer is 
encouraged, unless someone comes up with a better idea for any of the weapons.
```

Original issue reported on code.google.com by `gwessner` on 13 Jun 2010 at 6:24

**Comment by alazefhir** [comment]
Weapon grafics are almost completed: we are currently missing the following: 
-morphed weapon
-powered morphed weapon
-powered staff

**Comment by Blasphemer** [comment]
All weapons slots are filled, but the staff could benefit from additional refining\replacement
